services:
  - type: web
    name: recipe-recommender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:8000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
